services:
  - type: web
    name: ultimate-music-bot-v2
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: LAVALINK_HOST
        value: pnode1.danbot.host
      - key: LAVALINK_PORT
        value: 1351
      - key: LAVALINK_PASSWORD
        value: cocaine
      - key: LAVALINK_SECURE
        value: false
      - key: DB_PATH
        value: premium.db
      - key: PORT
        value: 10000
